---
title: 第九章：异常、模块与包
date: 2024-03-20 21:24:39
permalink: /pages/63f8e1/
categories:
  - python
  - python基础
tags:
    -
---
## 什么是异常
当检测到一个错误时，Python解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的“异常”，也就是我们常说的BUG

## 异常的捕获方法
### 捕获常规异常
基本语法：
```py
try:
  可能发生错误的代码
except:
  如果出现异常执行的代码
```

快速入门  
需求：尝试以`r`模式打开文件，如果文件不存在，则以`w`方式打开。
```py
try:
  f = open('linux.txt','r')
except:
  f = open('linux.txt','w')
```

### 捕获指定异常
基本语法：
```py
try:
  print(name)
except NameError as e:
  print('name变量名称未定义错误')
```

::: warning
- 如果尝试执行的代码的异常类型和要捕获的异常类型不一致，则无法捕获异常。  
- 一般try下方只放一行尝试执行的代码
:::

### 捕获多个异常
当捕获多个异常时，可以把要捕获的异常类型的名字，放到except后，并使用元组的方式进行书写。
```py
try:
  print(1/0)
except(NameError, ZeroDivisionError):
  print('ZeroDivisionErro错误...')
```

### 捕获所有异常
```py
try:
  1 / 0
except Exception as e:
  print("出现异常了")
```

### 异常else
else表示的是如果没有异常要执行的代码。
```py
try:
  print(1)
except Exception as e:
  print(e)
else:
  print('我是else,是没有异常的时候执行的代码')
```

### 异常的finally
finally表示的是无论是否异常都要执行的代码，例如关闭文件：
```py
try:
  f = open('test.txt', 'r')
except Exception as e:
  f = open('test.txt', 'w')
else:
  print("没有异常真开心")
finally:
  f.close()
```

## 异常的传递
异常具有传递性的

当函数func01中发生异常，并且没有捕获处理这个异常的时候，异常会传递到函数func02,当func02也没有捕获处理这个异常的时候，main函数会捕获这个异常，这就是异常的传递性。

提示：  
当所有函数都没有捕获异常的时候，程序就会报错。  

```py
def func01():
  print('这是func01开始')
  num = 1 / 0
  print('这是func01结束')

def func02():
  print("这是func02开始")
  func01()
  print("这是func02结束")

def main():
  try:
    func02()
  except Exception as e:
    print(e)
```

## Python模块
### 什么是模块
Python模块，是一个Python文件，以.py结尾，模块能定义函数，类和变量，模块能定义函数，类和变量，模块里也能包含可执行的代码。

### 模块的作用
python中有很多不同的模块，每个模块都可以帮助我们快速的实现一些功能，比如实现和时间相关的功能就可以使用time模块，我们可以任务一个模块就是一个工具包，每一个工具包中都有各种不同的工具供我们使用进而实现各种不同的功能。

### 模块的导入方式
模块在使用前需要先导入，导入的语法如下：  
[from 模块名] import [模块 | 类 | 变量 | 函数 | *] [as 别名]  
常用的组合形式如：  
- import 模块名  
- from 模块名 import 类、变量、方法等  
- from 模块名 import *  
- import 模块名 as 别名  
- from 模块名 import 功能名 as 别名  